---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  # enable detailed explanations available in cops
  # the default output is not enough to understand what is wrong
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  # perefer brackets for `grep-ability`
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - config/**/*
  AllowedMethods: []

Layout/LineLength:
  Exclude: []
  # ignore heredoc for readability
  AllowHeredoc: true
  # URLs are almost always long
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true

Style/ClassAndModuleChildren:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false
